### ISSUE TITLE
Division by Zero?

### ISSUE THREAD

**Issue by collinskatie** [embodied-computation-group/metadPy#3]
Hi, thank you for making this great tool! 

I am trying to compute meta-d' on data with continuous confidence scores (between 0 and 1). I've created a data frame with Stimuli, Responses, Confidence, nTrial, and Subject column headers.

<img width="628" alt="Screenshot 2022-05-15 at 12 38 40" src="https://user-images.githubusercontent.com/37914552/168470862-91b666a4-8085-4731-af7f-9bf47be52045.png">

(there are 10,000 rows -- 1,000 of which are stimuli 1, with 992 responses for stimuli 1) 

I am able to compute .dprime() on this data frame without errors.

However, when I run the meta-d' code provided in the README (removing the 4-point rating scale, since this is continuous), I get a divide by zero error. 

`from metadPy.mle import metad`
`metad = metad(data=meta_d_df, stimuli='Stimuli',
              accuracy='Accuracy', confidence='Confidence', verbose=0)`
`print(f'meta-d\' = {str(metad["meta_d"])}')`

<img width="695" alt="Screenshot 2022-05-15 at 12 41 42" src="https://user-images.githubusercontent.com/37914552/168470975-d37df781-5859-4541-b5af-e7e1d0390c17.png">

Do you know why this may be happening? Is there a different command I should run when I have continuous confidence ratings? 

If useful, attached is the data frame I'm using: 
[sample_meta_d_prime.csv](https://github.com/embodied-computation-group/metadPy/files/8694844/sample_meta_d_prime.csv)

Thank you for any help, and thanks again for providing this tool!

**Comment by LegrandNico** [comment]
Hi @collinskatie , sorry for the late reply. It looks like this is due to the continuous rating scale. Confidence ratings are always discretized to estimate metad, and the dprime is not using the confidence, just the stimulus-responses columns. You can use metadPy.uils.discreRatings to transform your column into e.g 4 points scale (which is the default for most studies), and then pass your data frame the same way you did, and remember to specify the corresponding number of ratings.

**Comment by collinskatie** [comment]
Thank works perfectly! Thank you, @LegrandNico !

**Comment by LegrandNico** [comment]
Excellent! Let me know if there is another issue.
