### ISSUE TITLE
Bayesian Fit: `TypeError: __init__()`

### ISSUE THREAD

**Issue by minor** [embodied-computation-group/metadPy#4]
Hi,

I'm trying to find `hmeta-d` through `numpyro` but it seems that the examples are not working.

When running [Estimating meta-d' (single subject) using Bayesian modelling - Numpyro](https://colab.research.google.com/github/embodied-computation-group/metadPy/blob/master/notebooks/Example%202%20-%20Fitting%20Bayesian%20-%20Subject%20level%20(numpyro).ipynb) and [Estimating meta-d' (single subject) using Bayesian modelling - pymc](https://colab.research.google.com/github/embodied-computation-group/metadPy/blob/master/notebooks/Example%202%20-%20Fitting%20Bayesian%20-%20Subject%20level%20(pymc).ipynb) (which by the way, the link asks for GitHub authorization right now), I get the following error:
`TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given`

I am attaching two screenshots showing that it happens not just through response-signal arrays, but also through dataframes:
![CleanShot 2022-06-27 at 18 57 25](https://user-images.githubusercontent.com/31828155/176072836-805f3f6d-f85d-480a-a15b-ecfe4f39fbca.jpg)
![CleanShot 2022-06-27 at 18 57 51](https://user-images.githubusercontent.com/31828155/176072856-da937a17-c9f3-4b5a-afbd-c1784336b919.jpg)

Could you please help me out? I'm unsure how to resolve this issue. 

Thanks!

**Comment by LegrandNico** [comment]
Hi @minor , thank you for reporting that.

This bug appears with Numpyro 0.9.2 and is due to the format used to pass the data to the model function, which is now raising an error starting from this version. The model should work fine if you use Numpyro 0.9.1. 

I do not plan to fix this for now as the toolbox will probably only rely on PyMC and Aesara in the future, as it is more flexible for most users. Could you try using `backend=pymc` and see if this is working fine for you?

**Comment by minor** [comment]
Thanks for getting back to me! I tried using `backend=pymc` and it works now – thank you!
